server:
  port: 9091
  error:
    include-message: always
    include-binding-errors: always

  servlet:
    session:
      timeout: 30m
      cookie:
        same-site: none
        secure: true

  # Optional: Set session expiration (e.g., 30 minutes)
#  server.servlet.session.timeout=30m

spring:
  application:
    name: user-product-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/delivery_db}
    username: ${SPRING_DATASOURCE_USERNAME:duetto}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9093}
    consumer:
      group-id: user-product-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 10MB
jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
  expiration: ${JWT_EXPIRATION:86400000}

management:
  metrics:
    tags:
      # This injects a global tag 'application="my-payment-service"' into every metric line
      application: ${spring.application.name}
  # 1. This exposes the endpoints to the web/HTTP engine
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: ["health", "info", "prometheus", "metrics"]

  # 2. This configures the behaviors of specific endpoints
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
    prometheus:
      enabled: true

  # 3. This enables specific indicators inside the health groups
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

logging:
  level:
    com.example.userproduct: INFO
    org.springframework.security: DEBUG

# SpringDoc OpenAPI Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    tags-sorter: alpha
    operations-sorter: alpha
  show-actuator: false
  packages-to-scan: com.example.userproduct.controller
  packages-to-exclude: com.example.userproduct.entities
  default-produces-media-type: application/json
  default-consumes-media-type: application/json

file:
  upload-dir: ${user.home}/test/resource

sms:
  service:
    enabled: true
    message-text: Hello world!!!
